# [provider]
# cluster = "localnet"
# wallet = "~/.config/solana/id.json"

# [programs.localnet]
# basic_0 = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

# [scripts]
# test = "mocha -t 1000000 tests/"

[provider]
cluster = "http://127.0.0.1:8899"
# cluster = "https://api.devnet.solana.com/"
wallet = "./keypair.json"