# [provider]
# cluster = "localnet"
# wallet = "~/.config/solana/id.json"

[programs.localnet]
oracle = "A9DXGTCMLJsX7kMfwJ2aBiAFACPmUsxv6TRxcEohL4CD"

# [scripts]
# test = "mocha -t 1000000 tests/"

[provider]
cluster = "http://127.0.0.1:8899"
# cluster = "https://api.devnet.solana.com/"
wallet = "./keys/localnet/owner.json"