[workspace]
members = [
    "programs/*",
    "programs/scope/types",
    "off_chain/scope-cli",
    "off_chain/orbit-link"
]
resolver = "2"

[profile.dev]
overflow-checks = true

[profile.release]
lto = "thin"
overflow-checks = true
