[package]
name = "scope"
version = "0.1.0"
description = "Scope is Hubble's oracle aggregator"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "scope"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.22.0"
anchor-spl = { version = "0.22.0", features = ["token"] }
spl-token = { version = "3.1.1", features = ["no-entrypoint"] }
num_enum = "0.5.6"
pyth-client = "0.2.2"
serde = "1.0.136"
num-traits = "0.2.14"

[build-dependencies]
serde = "1.0.136"
serde_json = "1.0.79"
anyhow = "1.0.54"
