[package]
name = "scope"
version = "0.1.0"
description = "Scope is Hubble's oracle aggregator"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "scope"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.20.1"
num_enum = "0.5.6"
pyth-client = "0.2.2"

[build-dependencies]
serde = "1.0.136"
serde_json = "1.0.79"
anyhow = "1.0.54"
