[package]
name = "scope"
version = "0.1.0"
description = "Scope is Hubble's oracle aggregator"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "scope"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
skip_price_validation = []

# If none of the following is set, one will be selected based on env $CLUSTER variable
# If $CLUSTER is not set either, default will be mainnet
devnet = ["skip_price_validation"]
localnet = []
mainnet = []

[dependencies]
anchor-lang = "~0.20.1"
anchor-spl = { version = "~0.20.1", features = ["token"] }
spl-token = { version = "3.1.1", features = ["no-entrypoint"] }
num_enum = "0.5.6"
pyth-client = "0.2.2"
cfg-if = "1.0.0"
serde = "1.0.136"
switchboard-program = "0.2.0"
switchboard-v2 = "0.1.3"
solend-program = { git = "https://github.com/solendprotocol/solana-program-library", features = [
    "no-entrypoint",
] }
