name: Typescript Prettier

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prettify code
        uses: creyD/prettier_action@v4.1.1
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --check ./**/*.ts
