name: Integration tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ts-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hubbleprotocol/solana-setup-action@v0.1
        with:
          solana-version: v1.13.6
          rust-version: stable
          anchor-version: v0.26.0
          setup-node: 19

      - name: build programs
        run: |
          make build
      - name: test
        run: |
          make test-validator > validator.logs 2>&1 &
          sleep 15
          make airdrop
          make deploy
          make test-ts
